@startuml
namespace github.com\\hyperledger\\fabric\\core\\endorser {
 class chaincodeError {
  status int32
  msg string
}
}
namespace github.com\\hyperledger\\fabric\\core\\endorser {
 class Endorser {
  policyChecker policy.PolicyChecker
}
}
@enduml